Mean

In [ ]:
num_list = [21, 11, 19, 3,11,5]
# FInd sum of the numbers
num_sum = sum(num_list)
#divide the sum with length of the list
mean = num_sum / len(num_list)
print(num_list)
print("Mean of the above list of numbers is: " + str(round(mean,2)))

[21, 11, 19, 3, 11, 5]
Mean of the above list of numbers is: 11.67

Median

In [ ]:
# Python program to print
# median of elements

# list of elements to calculate median
n_num = [1, 2, 3, 4, 5]
n = len(n_num)
n_num.sort()

if n % 2 == 0:
	median1 = n_num[n//2]
	median2 = n_num[n//2 - 1]
	median = (median1 + median2)/2
else:
	median = n_num[n//2]
print("Median is: " + str(median))

Median is: 3

IQR

In [ ]:
import numpy as np

In [ ]:
#First Quartile
Q1=np.median(n_num[:4])
print("Q1 is:",Q1)
##Third Quartile
Q3=np.median(n_num[4:])
print("Q3 is:",Q3)
##IQR
IQR=Q3-Q1
print("IQR is",IQR)

Q1 is: 2.5
Q3 is: 5.0
IQR is 2.5

Rolling a dice

In [ ]:
import random
count=[0,0,0,0,0,0]
for i in range(10000):
  count[random.randint(0,5)]+=1
  for i in range(6):
    print("value %d happened %d times" %(i+1,count[i]))

Streaming output truncated to the last 5000 lines.
value 5 happened 1541 times
value 6 happened 1509 times
value 1 happened 1574 times
value 2 happened 1546 times
value 3 happened 1503 times
value 4 happened 1494 times
value 5 happened 1541 times
value 6 happened 1510 times
value 1 happened 1574 times
value 2 happened 1546 times
value 3 happened 1503 times
value 4 happened 1494 times
value 5 happened 1542 times
value 6 happened 1510 times
value 1 happened 1574 times
value 2 happened 1546 times
value 3 happened 1503 times
value 4 happened 1494 times
value 5 happened 1543 times
value 6 happened 1510 times
value 1 happened 1574 times
value 2 happened 1546 times
value 3 happened 1503 times
value 4 happened 1495 times
value 5 happened 1543 times
value 6 happened 1510 times
value 1 happened 1574 times
value 2 happened 1546 times
value 3 happened 1503 times
value 4 happened 1495 times
value 5 happened 1543 times
value 6 happened 1511 times
value 1 happened 1574 times
value 2 happened 1546 times
value 3 happened 1503 times
value 4 happened 1495 times
value 5 happened 1543 times
value 6 happened 1512 times
value 1 happened 1574 times
value 2 happened 1546 times
value 3 happened 1503 times
value 4 happened 1495 times
value 5 happened 1544 times
value 6 happened 1512 times
value 1 happened 1574 times
value 2 happened 1546 times
value 3 happened 1503 times
value 4 happened 1495 times
value 5 happened 1544 times
value 6 happened 1513 times
value 1 happened 1574 times
value 2 happened 1546 times
value 3 happened 1503 times
value 4 happened 1495 times
value 5 happened 1544 times
value 6 happened 1514 times
value 1 happened 1575 times
value 2 happened 1546 times
value 3 happened 1503 times
value 4 happened 1495 times
value 5 happened 1544 times
value 6 happened 1514 times
value 1 happened 1575 times
value 2 happened 1546 times
value 3 happened 1503 times
value 4 happened 1495 times
value 5 happened 1545 times
value 6 happened 1514 times
value 1 happened 1575 times
value 2 happened 1546 times
value 3 happened 1504 times
value 4 happened 1495 times
value 5 happened 1545 times
value 6 happened 1514 times
value 1 happened 1575 times
value 2 happened 1546 times
value 3 happened 1504 times
value 4 happened 1495 times
value 5 happened 1545 times
value 6 happened 1515 times
value 1 happened 1575 times
value 2 happened 1546 times
value 3 happened 1504 times
value 4 happened 1495 times
value 5 happened 1545 times
value 6 happened 1516 times
value 1 happened 1575 times
value 2 happened 1546 times
value 3 happened 1504 times
value 4 happened 1496 times
value 5 happened 1545 times
value 6 happened 1516 times
value 1 happened 1575 times
value 2 happened 1546 times
value 3 happened 1504 times
value 4 happened 1496 times
value 5 happened 1545 times
value 6 happened 1517 times
value 1 happened 1576 times
value 2 happened 1546 times
value 3 happened 1504 times
value 4 happened 1496 times
value 5 happened 1545 times
value 6 happened 1517 times
value 1 happened 1576 times
value 2 happened 1547 times
value 3 happened 1504 times
value 4 happened 1496 times
value 5 happened 1545 times
value 6 happened 1517 times
value 1 happened 1576 times
value 2 happened 1548 times
value 3 happened 1504 times
value 4 happened 1496 times
value 5 happened 1545 times
value 6 happened 1517 times
value 1 happened 1576 times
value 2 happened 1548 times
value 3 happened 1504 times
value 4 happened 1496 times
value 5 happened 1545 times
value 6 happened 1518 times
value 1 happened 1576 times
value 2 happened 1548 times
value 3 happened 1504 times
value 4 happened 1496 times
value 5 happened 1545 times
value 6 happened 1519 times
value 1 happened 1577 times
value 2 happened 1548 times
value 3 happened 1504 times
value 4 happened 1496 times
value 5 happened 1545 times
value 6 happened 1519 times
value 1 happened 1577 times
value 2 happened 1548 times
value 3 happened 1504 times
value 4 happened 1497 times
value 5 happened 1545 times
value 6 happened 1519 times
value 1 happened 1577 times
value 2 happened 1548 times
value 3 happened 1504 times
value 4 happened 1497 times
value 5 happened 1545 times
value 6 happened 1520 times
value 1 happened 1577 times
value 2 happened 1548 times
value 3 happened 1504 times
value 4 happened 1497 times
value 5 happened 1545 times
value 6 happened 1521 times
value 1 happened 1577 times
value 2 happened 1548 times
value 3 happened 1504 times
value 4 happened 1497 times
value 5 happened 1546 times
value 6 happened 1521 times
value 1 happened 1577 times
value 2 happened 1548 times
value 3 happened 1504 times
value 4 happened 1497 times
value 5 happened 1546 times
value 6 happened 1522 times
value 1 happened 1577 times
value 2 happened 1548 times
value 3 happened 1504 times
value 4 happened 1497 times
value 5 happened 1546 times
value 6 happened 1523 times
value 1 happened 1577 times
value 2 happened 1549 times
value 3 happened 1504 times
value 4 happened 1497 times
value 5 happened 1546 times
value 6 happened 1523 times
value 1 happened 1577 times
value 2 happened 1549 times
value 3 happened 1505 times
value 4 happened 1497 times
value 5 happened 1546 times
value 6 happened 1523 times
value 1 happened 1577 times
value 2 happened 1549 times
value 3 happened 1506 times
value 4 happened 1497 times
value 5 happened 1546 times
value 6 happened 1523 times
value 1 happened 1577 times
value 2 happened 1549 times
value 3 happened 1507 times
value 4 happened 1497 times
value 5 happened 1546 times
value 6 happened 1523 times
value 1 happened 1577 times
value 2 happened 1549 times
value 3 happened 1507 times
value 4 happened 1498 times
value 5 happened 1546 times
value 6 happened 1523 times
value 1 happened 1577 times
value 2 happened 1549 times
value 3 happened 1507 times
value 4 happened 1499 times
value 5 happened 1546 times
value 6 happened 1523 times
value 1 happened 1577 times
value 2 happened 1549 times
value 3 happened 1507 times
value 4 happened 1499 times
value 5 happened 1546 times
value 6 happened 1524 times
value 1 happened 1578 times
value 2 happened 1549 times
value 3 happened 1507 times
value 4 happened 1499 times
value 5 happened 1546 times
value 6 happened 1524 times
value 1 happened 1578 times
value 2 happened 1549 times
value 3 happened 1507 times
value 4 happened 1500 times
value 5 happened 1546 times
value 6 happened 1524 times
value 1 happened 1578 times
value 2 happened 1550 times
value 3 happened 1507 times
value 4 happened 1500 times
value 5 happened 1546 times
value 6 happened 1524 times
value 1 happened 1578 times
value 2 happened 1550 times
value 3 happened 1507 times
value 4 happened 1500 times
value 5 happened 1547 times
value 6 happened 1524 times
value 1 happened 1578 times
value 2 happened 1550 times
value 3 happened 1507 times
value 4 happened 1500 times
value 5 happened 1548 times
value 6 happened 1524 times
value 1 happened 1578 times
value 2 happened 1550 times
value 3 happened 1507 times
value 4 happened 1500 times
value 5 happened 1548 times
value 6 happened 1525 times
value 1 happened 1579 times
value 2 happened 1550 times
value 3 happened 1507 times
value 4 happened 1500 times
value 5 happened 1548 times
value 6 happened 1525 times
value 1 happened 1579 times
value 2 happened 1550 times
value 3 happened 1507 times
value 4 happened 1500 times
value 5 happened 1549 times
value 6 happened 1525 times
value 1 happened 1579 times
value 2 happened 1550 times
value 3 happened 1507 times
value 4 happened 1501 times
value 5 happened 1549 times
value 6 happened 1525 times
value 1 happened 1580 times
value 2 happened 1550 times
value 3 happened 1507 times
value 4 happened 1501 times
value 5 happened 1549 times
value 6 happened 1525 times
value 1 happened 1580 times
value 2 happened 1551 times
value 3 happened 1507 times
value 4 happened 1501 times
value 5 happened 1549 times
value 6 happened 1525 times
value 1 happened 1581 times
value 2 happened 1551 times
value 3 happened 1507 times
value 4 happened 1501 times
value 5 happened 1549 times
value 6 happened 1525 times
value 1 happened 1582 times
value 2 happened 1551 times
value 3 happened 1507 times
value 4 happened 1501 times
value 5 happened 1549 times
value 6 happened 1525 times
value 1 happened 1582 times
value 2 happened 1551 times
value 3 happened 1507 times
value 4 happened 1501 times
value 5 happened 1549 times
value 6 happened 1526 times
value 1 happened 1582 times
value 2 happened 1551 times
value 3 happened 1508 times
value 4 happened 1501 times
value 5 happened 1549 times
value 6 happened 1526 times
value 1 happened 1582 times
value 2 happened 1551 times
value 3 happened 1509 times
value 4 happened 1501 times
value 5 happened 1549 times
value 6 happened 1526 times
value 1 happened 1582 times
value 2 happened 1552 times
value 3 happened 1509 times
value 4 happened 1501 times
value 5 happened 1549 times
value 6 happened 1526 times
value 1 happened 1582 times
value 2 happened 1552 times
value 3 happened 1509 times
value 4 happened 1501 times
value 5 happened 1550 times
value 6 happened 1526 times
value 1 happened 1582 times
value 2 happened 1552 times
value 3 happened 1509 times
value 4 happened 1501 times
value 5 happened 1550 times
value 6 happened 1527 times
value 1 happened 1582 times
value 2 happened 1552 times
value 3 happened 1509 times
value 4 happened 1501 times
value 5 happened 1551 times
value 6 happened 1527 times
value 1 happened 1582 times
value 2 happened 1552 times
value 3 happened 1509 times
value 4 happened 1501 times
value 5 happened 1552 times
value 6 happened 1527 times
value 1 happened 1582 times
value 2 happened 1552 times
value 3 happened 1510 times
value 4 happened 1501 times
value 5 happened 1552 times
value 6 happened 1527 times
value 1 happened 1582 times
value 2 happened 1552 times
value 3 happened 1510 times
value 4 happened 1502 times
value 5 happened 1552 times
value 6 happened 1527 times
value 1 happened 1583 times
value 2 happened 1552 times
value 3 happened 1510 times
value 4 happened 1502 times
value 5 happened 1552 times
value 6 happened 1527 times
value 1 happened 1583 times
value 2 happened 1552 times
value 3 happened 1510 times
value 4 happened 1502 times
value 5 happened 1552 times
value 6 happened 1528 times
value 1 happened 1583 times
value 2 happened 1553 times
value 3 happened 1510 times
value 4 happened 1502 times
value 5 happened 1552 times
value 6 happened 1528 times
value 1 happened 1583 times
value 2 happened 1553 times
value 3 happened 1510 times
value 4 happened 1502 times
value 5 happened 1553 times
value 6 happened 1528 times
value 1 happened 1583 times
value 2 happened 1553 times
value 3 happened 1511 times
value 4 happened 1502 times
value 5 happened 1553 times
value 6 happened 1528 times
value 1 happened 1583 times
value 2 happened 1553 times
value 3 happened 1511 times
value 4 happened 1503 times
value 5 happened 1553 times
value 6 happened 1528 times
value 1 happened 1583 times
value 2 happened 1554 times
value 3 happened 1511 times
value 4 happened 1503 times
value 5 happened 1553 times
value 6 happened 1528 times
value 1 happened 1583 times
value 2 happened 1555 times
value 3 happened 1511 times
value 4 happened 1503 times
value 5 happened 1553 times
value 6 happened 1528 times
value 1 happened 1583 times
value 2 happened 1555 times
value 3 happened 1512 times
value 4 happened 1503 times
value 5 happened 1553 times
value 6 happened 1528 times
value 1 happened 1583 times
value 2 happened 1555 times
value 3 happened 1512 times
value 4 happened 1503 times
value 5 happened 1554 times
value 6 happened 1528 times
value 1 happened 1583 times
value 2 happened 1555 times
value 3 happened 1513 times
value 4 happened 1503 times
value 5 happened 1554 times
value 6 happened 1528 times
value 1 happened 1583 times
value 2 happened 1555 times
value 3 happened 1513 times
value 4 happened 1503 times
value 5 happened 1555 times
value 6 happened 1528 times
value 1 happened 1583 times
value 2 happened 1556 times
value 3 happened 1513 times
value 4 happened 1503 times
value 5 happened 1555 times
value 6 happened 1528 times
value 1 happened 1583 times
value 2 happened 1556 times
value 3 happened 1513 times
value 4 happened 1503 times
value 5 happened 1555 times
value 6 happened 1529 times
value 1 happened 1583 times
value 2 happened 1556 times
value 3 happened 1514 times
value 4 happened 1503 times
value 5 happened 1555 times
value 6 happened 1529 times
value 1 happened 1583 times
value 2 happened 1556 times
value 3 happened 1514 times
value 4 happened 1503 times
value 5 happened 1555 times
value 6 happened 1530 times
value 1 happened 1584 times
value 2 happened 1556 times
value 3 happened 1514 times
value 4 happened 1503 times
value 5 happened 1555 times
value 6 happened 1530 times
value 1 happened 1584 times
value 2 happened 1556 times
value 3 happened 1514 times
value 4 happened 1504 times
value 5 happened 1555 times
value 6 happened 1530 times
value 1 happened 1584 times
value 2 happened 1557 times
value 3 happened 1514 times
value 4 happened 1504 times
value 5 happened 1555 times
value 6 happened 1530 times
value 1 happened 1584 times
value 2 happened 1557 times
value 3 happened 1514 times
value 4 happened 1505 times
value 5 happened 1555 times
value 6 happened 1530 times
value 1 happened 1585 times
value 2 happened 1557 times
value 3 happened 1514 times
value 4 happened 1505 times
value 5 happened 1555 times
value 6 happened 1530 times
value 1 happened 1585 times
value 2 happened 1557 times
value 3 happened 1514 times
value 4 happened 1505 times
value 5 happened 1556 times
value 6 happened 1530 times
value 1 happened 1585 times
value 2 happened 1557 times
value 3 happened 1515 times
value 4 happened 1505 times
value 5 happened 1556 times
value 6 happened 1530 times
value 1 happened 1585 times
value 2 happened 1558 times
value 3 happened 1515 times
value 4 happened 1505 times
value 5 happened 1556 times
value 6 happened 1530 times
value 1 happened 1586 times
value 2 happened 1558 times
value 3 happened 1515 times
value 4 happened 1505 times
value 5 happened 1556 times
value 6 happened 1530 times
value 1 happened 1586 times
value 2 happened 1559 times
value 3 happened 1515 times
value 4 happened 1505 times
value 5 happened 1556 times
value 6 happened 1530 times
value 1 happened 1586 times
value 2 happened 1559 times
value 3 happened 1515 times
value 4 happened 1506 times
value 5 happened 1556 times
value 6 happened 1530 times
value 1 happened 1587 times
value 2 happened 1559 times
value 3 happened 1515 times
value 4 happened 1506 times
value 5 happened 1556 times
value 6 happened 1530 times
value 1 happened 1587 times
value 2 happened 1559 times
value 3 happened 1515 times
value 4 happened 1506 times
value 5 happened 1557 times
value 6 happened 1530 times
value 1 happened 1588 times
value 2 happened 1559 times
value 3 happened 1515 times
value 4 happened 1506 times
value 5 happened 1557 times
value 6 happened 1530 times
value 1 happened 1588 times
value 2 happened 1559 times
value 3 happened 1515 times
value 4 happened 1506 times
value 5 happened 1557 times
value 6 happened 1531 times
value 1 happened 1588 times
value 2 happened 1559 times
value 3 happened 1515 times
value 4 happened 1507 times
value 5 happened 1557 times
value 6 happened 1531 times
value 1 happened 1589 times
value 2 happened 1559 times
value 3 happened 1515 times
value 4 happened 1507 times
value 5 happened 1557 times
value 6 happened 1531 times
value 1 happened 1589 times
value 2 happened 1559 times
value 3 happened 1515 times
value 4 happened 1507 times
value 5 happened 1557 times
value 6 happened 1532 times
value 1 happened 1590 times
value 2 happened 1559 times
value 3 happened 1515 times
value 4 happened 1507 times
value 5 happened 1557 times
value 6 happened 1532 times
value 1 happened 1590 times
value 2 happened 1559 times
value 3 happened 1515 times
value 4 happened 1507 times
value 5 happened 1557 times
value 6 happened 1533 times
value 1 happened 1590 times
value 2 happened 1559 times
value 3 happened 1515 times
value 4 happened 1508 times
value 5 happened 1557 times
value 6 happened 1533 times
value 1 happened 1590 times
value 2 happened 1559 times
value 3 happened 1515 times
value 4 happened 1508 times
value 5 happened 1558 times
value 6 happened 1533 times
value 1 happened 1590 times
value 2 happened 1559 times
value 3 happened 1516 times
value 4 happened 1508 times
value 5 happened 1558 times
value 6 happened 1533 times
value 1 happened 1590 times
value 2 happened 1559 times
value 3 happened 1516 times
value 4 happened 1508 times
value 5 happened 1559 times
value 6 happened 1533 times
value 1 happened 1590 times
value 2 happened 1559 times
value 3 happened 1517 times
value 4 happened 1508 times
value 5 happened 1559 times
value 6 happened 1533 times
value 1 happened 1590 times
value 2 happened 1559 times
value 3 happened 1518 times
value 4 happened 1508 times
value 5 happened 1559 times
value 6 happened 1533 times
value 1 happened 1590 times
value 2 happened 1559 times
value 3 happened 1518 times
value 4 happened 1508 times
value 5 happened 1559 times
value 6 happened 1534 times
value 1 happened 1590 times
value 2 happened 1559 times
value 3 happened 1519 times
value 4 happened 1508 times
value 5 happened 1559 times
value 6 happened 1534 times
value 1 happened 1590 times
value 2 happened 1559 times
value 3 happened 1519 times
value 4 happened 1509 times
value 5 happened 1559 times
value 6 happened 1534 times
value 1 happened 1591 times
value 2 happened 1559 times
value 3 happened 1519 times
value 4 happened 1509 times
value 5 happened 1559 times
value 6 happened 1534 times
value 1 happened 1592 times
value 2 happened 1559 times
value 3 happened 1519 times
value 4 happened 1509 times
value 5 happened 1559 times
value 6 happened 1534 times
value 1 happened 1592 times
value 2 happened 1559 times
value 3 happened 1519 times
value 4 happened 1510 times
value 5 happened 1559 times
value 6 happened 1534 times
value 1 happened 1592 times
value 2 happened 1559 times
value 3 happened 1520 times
value 4 happened 1510 times
value 5 happened 1559 times
value 6 happened 1534 times
value 1 happened 1593 times
value 2 happened 1559 times
value 3 happened 1520 times
value 4 happened 1510 times
value 5 happened 1559 times
value 6 happened 1534 times
value 1 happened 1593 times
value 2 happened 1559 times
value 3 happened 1520 times
value 4 happened 1510 times
value 5 happened 1560 times
value 6 happened 1534 times
value 1 happened 1593 times
value 2 happened 1559 times
value 3 happened 1521 times
value 4 happened 1510 times
value 5 happened 1560 times
value 6 happened 1534 times
value 1 happened 1593 times
value 2 happened 1559 times
value 3 happened 1522 times
value 4 happened 1510 times
value 5 happened 1560 times
value 6 happened 1534 times
value 1 happened 1593 times
value 2 happened 1559 times
value 3 happened 1522 times
value 4 happened 1510 times
value 5 happened 1561 times
value 6 happened 1534 times
value 1 happened 1593 times
value 2 happened 1559 times
value 3 happened 1522 times
value 4 happened 1510 times
value 5 happened 1562 times
value 6 happened 1534 times
value 1 happened 1593 times
value 2 happened 1559 times
value 3 happened 1522 times
value 4 happened 1510 times
value 5 happened 1562 times
value 6 happened 1535 times
value 1 happened 1593 times
value 2 happened 1559 times
value 3 happened 1522 times
value 4 happened 1510 times
value 5 happened 1563 times
value 6 happened 1535 times
value 1 happened 1593 times
value 2 happened 1560 times
value 3 happened 1522 times
value 4 happened 1510 times
value 5 happened 1563 times
value 6 happened 1535 times
value 1 happened 1593 times
value 2 happened 1560 times
value 3 happened 1522 times
value 4 happened 1510 times
value 5 happened 1563 times
value 6 happened 1536 times
value 1 happened 1594 times
value 2 happened 1560 times
value 3 happened 1522 times
value 4 happened 1510 times
value 5 happened 1563 times
value 6 happened 1536 times
value 1 happened 1594 times
value 2 happened 1561 times